### ISSUE TITLE
Use the Wayback Machine's CDX server

### ISSUE THREAD

**Issue by willglynn** [muffinista/wayback_exe#1]
The Wayback Machine allows you to retrieve large lists of objects much more efficiently than spidering one page at a time.

For example, if you'd like a JSON list of `text/html` URLs within `tripod.com`, dating from 2001 to 2003, excluding redirects and error pages (i.e. only `200 OK` responses), with at most one result per URL, you can ask for that:

http://web.archive.org/cdx/search/cdx?url=tripod.com&output=json&from=2001&to=2003&filter=mimetype:text/html&filter=statuscode:200&collapse=urlkey&matchType=prefix

    [["urlkey","timestamp","original","mimetype","statuscode","digest","length"],
    ["com,tripod)/", "20010331190110", "http://www1.tripod.com:80/", "text/html", "200", "663APEX5DHJP3MK4Y5YXXCDFYY67GCFF", "563"],
    …
    ["com,tripod)/adm/interstitial/remote.html", "20020223061930", "http://www55.tripod.com:80/adm/interstitial/remote.html", "text/html", "200", "2W7D4CLILLLZ5UDTQNM6JPAT42S32PGY", "3023"],
    ["com,tripod)/aip01", "20010210190623", "http://www.tripod.com:80/aip01", "text/html", "200", "4CIZH4MK3C5RAYVNXGSXHPZVEVSPC4TW", "2545"],
    ["com,tripod)/belighter", "20010208131134", "http://www.tripod.com:80/belighter", "text/html", "200", "4CIZH4MK3C5RAYVNXGSXHPZVEVSPC4TW", "2546"],
    ["com,tripod)/biodata.htm", "20021004114145", "http://www453.tripod.com:80/biodata.htm", "text/html", "200", "ASR3MT7YH7E7P2LNYP56MG4HUOLG234O", "4747"],
    ["com,tripod)/boag3.midi", "20010211184616", "http://tripod.com:80/boag3.midi", "text/html", "200", "WFM7NZQQIXAVZMLWGBXX7GCK362YQYBB", "2520"],
    ["com,tripod)/book", "20010211120050", "http://www.tripod.com:80/book", "text/html", "200", "4CIZH4MK3C5RAYVNXGSXHPZVEVSPC4TW", "2543"],
    ["com,tripod)/britney/images/8.html", "20011225212501", "http://www212.tripod.com:80/britney/images/8.html", "text/html", "200", "EQ5FW3XRU2QB7WN2PW4Z5NBQU6QS77RX", "1923"],
    ["com,tripod)/britney/images/index.html", "20011225212500", "http://www212.tripod.com:80/britney/images/index.html", "text/html", "200", "U7PBHSQD4HCDPVA2LXFR4ZAJXY3PYJUE", "2669"],
    ["com,tripod)/britney/links.html", "20011225212504", "http://www212.tripod.com:80/britney/links.html", "text/html", "200", "7IET7565DYSH6GYVMH26TOTN7QOUJWY2", "2918"],
    ["com,tripod)/build", "20010201203700", "http://www.tripod.com:80/build", "text/html", "200", "4CIZH4MK3C5RAYVNXGSXHPZVEVSPC4TW", "2543"],
    ["com,tripod)/build/better_builders", "20010202180800", "http://www.tripod.com:80/build/better_builders", "text/html", "200", "4CIZH4MK3C5RAYVNXGSXHPZVEVSPC4TW", "2552"],
    …

Docs: https://github.com/internetarchive/wayback/blob/master/wayback-cdx-server/README.md

**Comment by muffinista** [comment]
Thanks for the suggestion. I actually spent awhile experimenting with CDX, and it's pretty amazing. 

Unfortunately for this project I don't think it works because I didn't want to specify a specific list of domains/URLs to work from. The discovery process of scraping is actually an important part of the project -- I'm hoping that it unearths a lot of interesting sites that aren't obvious and wouldn't be revealed if I was using CDX.

**Comment by willglynn** [comment]
You would still need to scrape pages to find new prefixes (e.g. `tripod.com`), but the CDX server would eliminate the need to identify content within a domain. The CDX data would also prevent you from following links that lead out of the archive, or retrieving URLs that are only available outside the target time period.

**Comment by muffinista** [comment]
That's very true, but the link following and time issues are both easily handled as well. At this point it's somewhat academic for the bot, as it has almost 30k URLs in the database and a pile more in the queue. But if someone makes a version using CDX I would love to see it!
